# Generated by Django 5.1.5 on 2025-02-09 13:35

import datetime
import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewCSVUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('access_pin', models.CharField(blank=True, max_length=10, null=True)),
                ('video_url', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='default_room.jpg', upload_to='room_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Guest', max_length=100)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('check_in_date', models.DateField(default=datetime.date.today)),
                ('check_out_date', models.DateField(default=main.models.default_check_out_date)),
                ('is_archived', models.BooleanField(default=False)),
                ('secure_token', models.CharField(blank=True, max_length=10, unique=True)),
                ('assigned_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.room')),
            ],
        ),
    ]
