# Generated by Django 5.1.5 on 2025-02-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='reservation_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
