# Generated by Django 5.1.5 on 2025-01-29 16:35

import datetime
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='check_in_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='guest',
            name='check_out_date',
            field=models.DateField(default=main.models.default_check_out_date),
        ),
        migrations.AddField(
            model_name='guest',
            name='full_name',
            field=models.CharField(default='Guest', max_length=100),
        ),
    ]
