# Generated by Django 5.1.5 on 2025-02-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_guest_reservation_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='is_returning',
            field=models.BooleanField(default=False),
        ),
    ]
