# Generated by Django 5.1.5 on 2025-01-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_guest_check_in_date_guest_check_out_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
