# Generated by Django 5.1.5 on 2025-01-31 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_guest_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='secure_token',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
