# Generated by Django 5.1.5 on 2025-02-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_guest_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='reservation_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
