# Generated by Django 5.1.5 on 2025-03-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_guest_reservation_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='lock_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
