# Generated by Django 5.1.5 on 2025-03-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_room_lock_id_alter_room_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_front_door', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='lock_id',
        ),
        migrations.AddField(
            model_name='guest',
            name='front_door_pin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='front_door_pin_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
