# Generated by Django 5.1.5 on 2025-03-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_room_access_pin_guest_room_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='room_pin',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='room_pin_id',
        ),
        migrations.AddField(
            model_name='room',
            name='access_pin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ttlock',
            name='lock_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.DeleteModel(
            name='TuyaLock',
        ),
    ]
