# Generated by Django 5.1.5 on 2025-03-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_guest_room_pin_remove_guest_room_pin_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='early_checkin_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='late_checkout_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
