# Generated by Django 5.1.5 on 2025-03-12 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_guest_early_checkin_time_guest_late_checkout_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='room_pin_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='ttlock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ttlock'),
        ),
    ]
