# Generated by Django 5.1.5 on 2025-03-12 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_room_access_pin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'permissions': [('can_give_access', 'Can give access to doors')]},
        ),
    ]
