# Generated by Django 5.1.5 on 2025-03-13 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_guest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'permissions': [('can_give_access', 'Can give access to doors'), ('view_admin_dashboard', 'Can view the admin dashboard and manage guests'), ('manage_rooms', 'Can manage rooms')]},
        ),
    ]
