# Generated by Django 5.1.5 on 2025-03-15 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_guest_id_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='id_image',
        ),
        migrations.CreateModel(
            name='GuestIDUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_image', models.ImageField(upload_to='guest_ids/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_uploads', to='main.guest')),
            ],
        ),
    ]
