# Generated by Django 5.1.5 on 2025-03-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_guest_id_image_guestidupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestidupload',
            name='id_image',
            field=models.CharField(max_length=500),
        ),
    ]
