# Generated by Django 5.1.5 on 2025-03-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_guestidupload_id_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
