# Generated by Django 5.1.5 on 2025-03-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_popularevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='dont_send_review_message',
            field=models.BooleanField(default=False),
        ),
    ]
