# Generated by Django 5.1.5 on 2025-10-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_guest_dont_send_review_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTLockToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TTLock Token',
                'verbose_name_plural': 'TTLock Tokens',
            },
        ),
    ]
