# Generated by Django 5.1.5 on 2025-10-21 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_ttlocktoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomICalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ical_url', models.URLField(help_text='iCal feed URL from Booking.com or Airbnb', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable polling for this room')),
                ('last_synced', models.DateTimeField(blank=True, help_text='Last successful sync timestamp', null=True)),
                ('last_sync_status', models.CharField(blank=True, help_text='Status of last sync attempt', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ical_config', to='main.room')),
            ],
            options={
                'verbose_name': 'Room iCal Configuration',
                'verbose_name_plural': 'Room iCal Configurations',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ical_uid', models.CharField(help_text='Unique identifier from iCal event (UID)', max_length=500, unique=True)),
                ('booking_reference', models.CharField(blank=True, help_text='Extracted booking reference (10-digit number)', max_length=50)),
                ('guest_name', models.CharField(help_text='Guest name from iCal SUMMARY', max_length=200)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('raw_ical_data', models.TextField(blank=True, help_text='Raw iCal event data for debugging')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.OneToOneField(blank=True, help_text='Linked Guest record (created after enrichment)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation', to='main.guest')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='main.room')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['-check_in_date'],
                'indexes': [models.Index(fields=['ical_uid'], name='main_reserv_ical_ui_50e0bd_idx'), models.Index(fields=['booking_reference'], name='main_reserv_booking_08dff2_idx'), models.Index(fields=['check_in_date'], name='main_reserv_check_i_9e0415_idx'), models.Index(fields=['status'], name='main_reserv_status_01eb99_idx')],
            },
        ),
    ]
