# Generated by Django 5.1.5 on 2025-10-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_roomicalconfig_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomicalconfig',
            name='ical_url',
        ),
        migrations.RemoveField(
            model_name='roomicalconfig',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='roomicalconfig',
            name='last_sync_status',
        ),
        migrations.RemoveField(
            model_name='roomicalconfig',
            name='last_synced',
        ),
        migrations.AddField(
            model_name='reservation',
            name='platform',
            field=models.CharField(choices=[('booking', 'Booking.com'), ('airbnb', 'Airbnb')], default='booking', help_text='Source platform (Booking.com or Airbnb)', max_length=20),
        ),
        migrations.AddField(
            model_name='roomicalconfig',
            name='airbnb_active',
            field=models.BooleanField(default=False, help_text='Enable Airbnb polling'),
        ),
        migrations.AddField(
            model_name='roomicalconfig',
            name='airbnb_ical_url',
            field=models.URLField(blank=True, help_text='Airbnb iCal feed URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='roomicalconfig',
            name='airbnb_last_sync_status',
            field=models.CharField(blank=True, help_text='Airbnb last sync status', max_length=255),
        ),
        migrations.AddField(
            model_name='roomicalconfig',
            name='airbnb_last_synced',
            field=models.DateTimeField(blank=True, help_text='Last Airbnb sync timestamp', null=True),
        ),
        migrations.AddField(
            model_name='roomicalconfig',
            name='booking_active',
            field=models.BooleanField(default=False, help_text='Enable Booking.com polling'),
        ),
        migrations.AddField(
            model_name='roomicalconfig',
            name='booking_ical_url',
            field=models.URLField(blank=True, help_text='Booking.com iCal feed URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='roomicalconfig',
            name='booking_last_sync_status',
            field=models.CharField(blank=True, help_text='Booking.com last sync status', max_length=255),
        ),
        migrations.AddField(
            model_name='roomicalconfig',
            name='booking_last_synced',
            field=models.DateTimeField(blank=True, help_text='Last Booking.com sync timestamp', null=True),
        ),
    ]
