# Generated by Django 5.1.5 on 2025-10-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_roomicalconfig_ical_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='early_checkin_time',
            field=models.TimeField(blank=True, help_text='Early check-in time (e.g., 12:00). If not set, defaults to 2:00 PM.', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='late_checkout_time',
            field=models.TimeField(blank=True, help_text='Late check-out time (e.g., 14:00). If not set, defaults to 11:00 AM.', null=True),
        ),
    ]
