# Generated by Django 5.1.5 on 2025-10-22 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_reservation_early_checkin_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('ical_welcome_email', 'iCal Welcome Email'), ('ical_welcome_sms', 'iCal Welcome SMS'), ('ical_update_email', 'iCal Update Email'), ('ical_update_sms', 'iCal Update SMS'), ('ical_cancellation_email', 'iCal Cancellation Email'), ('ical_cancellation_sms', 'iCal Cancellation SMS'), ('ical_post_stay_email', 'iCal Post-Stay Email'), ('ical_post_stay_sms', 'iCal Post-Stay SMS')], help_text='Type of message', max_length=50, unique=True)),
                ('subject', models.CharField(blank=True, help_text='Email subject (leave blank for SMS)', max_length=200)),
                ('content', models.TextField(help_text='Message content with variables like {guest_name}, {pin}, {room_name}')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this message without deleting it')),
                ('last_edited_at', models.DateTimeField(auto_now=True, help_text='Last edit timestamp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_edited_by', models.ForeignKey(blank=True, help_text='User who last edited', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Template',
                'verbose_name_plural': 'Message Templates',
                'ordering': ['message_type'],
            },
        ),
    ]
