# Generated by Django 5.1.5 on 2025-10-23 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_messagetemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVEnrichmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=255)),
                ('total_rows', models.IntegerField(default=0)),
                ('single_room_count', models.IntegerField(default=0)),
                ('multi_room_count', models.IntegerField(default=0)),
                ('created_count', models.IntegerField(default=0)),
                ('updated_count', models.IntegerField(default=0)),
                ('discrepancies_count', models.IntegerField(default=0)),
                ('errors_count', models.IntegerField(default=0)),
                ('enrichment_summary', models.JSONField(default=dict, help_text='Detailed results with enriched bookings and discrepancies')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CSV Enrichment Log',
                'verbose_name_plural': 'CSV Enrichment Logs',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PendingEnrichment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('booking', 'Booking.com')], default='booking', max_length=20)),
                ('booking_reference', models.CharField(db_index=True, max_length=50)),
                ('check_in_date', models.DateField(db_index=True)),
                ('email_type', models.CharField(choices=[('new', 'New Booking'), ('modification', 'Modification'), ('cancellation', 'Cancellation')], default='new', max_length=20)),
                ('email_received_at', models.DateTimeField(auto_now_add=True)),
                ('attempts', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending Match'), ('matched', 'Matched'), ('failed_awaiting_manual', 'Failed - Awaiting Manual Assignment'), ('manually_assigned', 'Manually Assigned'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=30)),
                ('alert_sent_at', models.DateTimeField(blank=True, null=True)),
                ('alert_sms_sid', models.CharField(blank=True, help_text='Twilio message SID', max_length=100)),
                ('manual_assignment_method', models.CharField(blank=True, choices=[('sms_reply', 'SMS Reply'), ('email_reply', 'Email Reply'), ('admin_ui', 'Admin UI')], max_length=20, null=True)),
                ('enriched_via', models.CharField(blank=True, choices=[('email_ical_auto', 'Email + iCal Auto-Match'), ('sms_reply', 'SMS Reply'), ('email_reply', 'Email Reply'), ('csv_upload', 'CSV Upload'), ('admin_manual', 'Admin Manual')], max_length=20, null=True)),
                ('enriched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_enrichments', to='main.reservation')),
                ('room_matched', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.room')),
            ],
            options={
                'verbose_name': 'Pending Enrichment',
                'verbose_name_plural': 'Pending Enrichments',
                'ordering': ['-email_received_at'],
            },
        ),
        migrations.CreateModel(
            name='EnrichmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('email_parsed', 'Email Parsed'), ('ical_synced', 'iCal Synced'), ('auto_matched_single', 'Auto-Matched Single Room'), ('auto_matched_multi_room', 'Auto-Matched Multi-Room'), ('xls_enriched_single', 'XLS Enriched Single Room'), ('xls_enriched_multi', 'XLS Enriched Multi-Room'), ('sms_reply_assigned', 'SMS Reply Assigned'), ('email_reply_assigned', 'Email Reply Assigned'), ('collision_detected', 'Collision Detected'), ('manual_admin_assigned', 'Manual Admin Assigned')], max_length=50)),
                ('booking_reference', models.CharField(db_index=True, max_length=50)),
                ('method', models.CharField(blank=True, max_length=50)),
                ('details', models.JSONField(default=dict, help_text='Additional context (room_count, rooms list, etc.)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrichment_logs', to='main.reservation')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.room')),
                ('pending_enrichment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='main.pendingenrichment')),
            ],
            options={
                'verbose_name': 'Enrichment Log',
                'verbose_name_plural': 'Enrichment Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='pendingenrichment',
            index=models.Index(fields=['booking_reference'], name='main_pendin_booking_7967fd_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingenrichment',
            index=models.Index(fields=['check_in_date'], name='main_pendin_check_i_bba36c_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingenrichment',
            index=models.Index(fields=['status'], name='main_pendin_status_a7106e_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingenrichment',
            index=models.Index(fields=['-email_received_at'], name='main_pendin_email_r_097309_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pendingenrichment',
            unique_together={('booking_reference', 'platform')},
        ),
        migrations.AddIndex(
            model_name='enrichmentlog',
            index=models.Index(fields=['booking_reference'], name='main_enrich_booking_076437_idx'),
        ),
        migrations.AddIndex(
            model_name='enrichmentlog',
            index=models.Index(fields=['-timestamp'], name='main_enrich_timesta_b238b1_idx'),
        ),
    ]
