# Generated by Django 5.1.5 on 2025-10-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_csvenrichmentlog_pendingenrichment_enrichmentlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='car_registration',
            field=models.CharField(blank=True, help_text="Guest's car registration number (optional)", max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='CheckInAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Django session key', max_length=100)),
                ('booking_reference', models.CharField(blank=True, help_text='Booking reference if entered', max_length=20, null=True)),
                ('step_reached', models.IntegerField(help_text='Last step reached (1-4)')),
                ('completed', models.BooleanField(default=False, help_text='Did guest complete full check-in?')),
                ('device_type', models.CharField(help_text='mobile or desktop', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Check-In Analytics',
                'verbose_name_plural': 'Check-In Analytics',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['session_id'], name='main_checki_session_bfe885_idx'), models.Index(fields=['booking_reference'], name='main_checki_booking_f20c97_idx'), models.Index(fields=['-started_at'], name='main_checki_started_98e045_idx')],
            },
        ),
    ]
