# Generated by Django 5.1.5 on 2025-10-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_guest_car_registration_checkinanalytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrichmentlog',
            name='action',
            field=models.CharField(choices=[('ical_new_booking', 'iCal: New Booking Detected'), ('collision_detected', 'Collision: Multiple Same-Day Bookings'), ('email_search_started', 'Email Search Started'), ('email_found_matched', 'Email Found and Matched'), ('email_not_found_alerted', 'Email Not Found - SMS Sent'), ('manual_enrichment_sms', 'Manual Enrichment via SMS'), ('multi_enrichment_sms', 'Multi-Booking Enrichment via SMS'), ('sms_reply_assigned', 'SMS Reply Assigned'), ('correction_applied', 'Correction Applied via SMS'), ('manual_admin_assigned', 'Manual Admin Assigned'), ('check_command_received', 'Check Command Received'), ('cancel_command_received', 'Cancel Command Received'), ('guide_command_received', 'Guide Command Received'), ('email_parsed', 'Email Parsed'), ('ical_synced', 'iCal Synced'), ('auto_matched_single', 'Auto-Matched Single Room'), ('auto_matched_multi_room', 'Auto-Matched Multi-Room'), ('xls_enriched_single', 'XLS Enriched Single Room'), ('xls_enriched_multi', 'XLS Enriched Multi-Room'), ('email_reply_assigned', 'Email Reply Assigned'), ('cancellation_detected', 'iCal: Booking Cancelled')], max_length=50),
        ),
    ]
