# Generated by Django 5.1.5 on 2025-10-27 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_add_multi_room_enrichment_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='guest',
            field=models.ForeignKey(blank=True, help_text='Linked Guest record (created after enrichment)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='main.guest'),
        ),
    ]
