# Generated by Django 5.1.5 on 2025-10-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_reservation_guest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popularevent',
            options={'ordering': ['-date', '-popularity_score']},
        ),
        migrations.AddField(
            model_name='popularevent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='popularevent',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='popularevent',
            name='is_sold_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='popularevent',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='popularevent',
            name='popularity_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='popularevent',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='popularevent',
            name='sms_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='popularevent',
            name='suggested_room_price',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='popularevent',
            name='ticket_max_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='popularevent',
            name='ticket_min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='popularevent',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='popularevent',
            name='event_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='popularevent',
            name='venue',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='popularevent',
            index=models.Index(fields=['date', 'popularity_score'], name='main_popula_date_6cda2b_idx'),
        ),
        migrations.AddIndex(
            model_name='popularevent',
            index=models.Index(fields=['venue', 'date'], name='main_popula_venue_aeca05_idx'),
        ),
        migrations.AddIndex(
            model_name='popularevent',
            index=models.Index(fields=['-popularity_score'], name='main_popula_popular_0db1cb_idx'),
        ),
    ]
